### ISSUE TITLE
Navigator not loading on HTTPS

### ISSUE THREAD

**Issue by OpenOilUG** [OpenOil-UG/tanzania#1]
Following error message:
Mixed Content: The page at 'https://openoil-ug.github.io/tanzania/tanzania/en/' was loaded over HTTPS, but requested an insecure resource 'http://tz.ohuiginn.net/tanzania.html?acacia'. This request has been blocked; the content must be served over HTTPS.

**Comment by danohu** [comment]
Fixed this; everything is under https
